services:
  web:
    build: .
    environment:
      - BLOG_DATABASE_PASSWORD
      - DATABASE_URL
      - RAILS_MASTER_KEY
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: /var/www/storage
        target: /rails/storage
